# Default values for kafka-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "kafka-connect-cluster"

version: 2.4.0
replicaCount: 1
bootstrapServers: localhost:9092

kafkaConnectAnnotations:
  strimzi.io/use-connector-resources: "true"

config:
  key.converter: org.apache.kafka.connect.json.JsonConverter
  value.converter: org.apache.kafka.connect.json.JsonConverter
  key.converter.schemas.enable: true
  value.converter.schemas.enable: true
  config.storage.replication.factor: 3
  offset.storage.replication.factor: 3
  status.storage.replication.factor: 3

jmvOptions:
  "-Xmx": "1g"
  "-Xms": "1g"

logging:
  type: inline
  loggers:
    log4j.rootLogger: "INFO"

readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
livenessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5

nodeSelector: {}

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi